remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/dark.css"

locale: en-GB
title: "Memory Palace"
description: "Occasional notes from an incomplete memory palace."
url: "https://markbarlow.github.io"
baseurl: "/memory-palace"

date_format: "%B %-d, %Y"
words_per_minute: 200

google_fonts:
  - name: "Newsreader"
    weights: "400,400i,700,700i"
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"

paginate: 10
paginate_path: /page:num/

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: false
